## 配置应用启动端口和编码信息
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /sso

## 配置mysql数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/?characterEncoding=UTF-8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
    name:
    ## 使用阿里巴巴Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  ## 配置Redis
  redis:
    host: 127.0.0.1
    post:6379
#    timeout:
  #    password:


## 配置mybatis，mybatis的mapping存储地址和mybatis实体类的包地址
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.microbank.sso.mybatis.mapper


## 配置JWT信息
jwt:
  clientId:13213213da1sad1sa5da
  secret:21a2s1da21dsadA&^Djhkjasdsalaskd
  name:microbank-sso
  expiresSecond:7200000

fastdfs:
  tracker_servers:10.20.8.252:22122
  connect_timeout_in_seconds:2
  network_timeout_in_seconds:30
  http_tracker_http_port:81
  charset:UTF-8
  http_url:http://10.20.8.252:81





