package com.chengzi.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class UserBaseInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.mobile_number
     *
     * @mbg.generated
     */
    private String mobileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.cert_no
     *
     * @mbg.generated
     */
    private String certNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.raw_add_time
     *
     * @mbg.generated
     */
    private Date rawAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.raw_update_time
     *
     * @mbg.generated
     */
    private Date rawUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_id
     *
     * @return the value of user_base_info.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_id
     *
     * @param userId the value for user_base_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.user_name
     *
     * @return the value of user_base_info.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.user_name
     *
     * @param userName the value for user_base_info.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.real_name
     *
     * @return the value of user_base_info.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.real_name
     *
     * @param realName the value for user_base_info.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.mobile_number
     *
     * @return the value of user_base_info.mobile_number
     *
     * @mbg.generated
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.mobile_number
     *
     * @param mobileNumber the value for user_base_info.mobile_number
     *
     * @mbg.generated
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber == null ? null : mobileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.cert_no
     *
     * @return the value of user_base_info.cert_no
     *
     * @mbg.generated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.cert_no
     *
     * @param certNo the value for user_base_info.cert_no
     *
     * @mbg.generated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.type
     *
     * @return the value of user_base_info.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.type
     *
     * @param type the value for user_base_info.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.state
     *
     * @return the value of user_base_info.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.state
     *
     * @param state the value for user_base_info.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.sex
     *
     * @return the value of user_base_info.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.sex
     *
     * @param sex the value for user_base_info.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.age
     *
     * @return the value of user_base_info.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.age
     *
     * @param age the value for user_base_info.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.raw_add_time
     *
     * @return the value of user_base_info.raw_add_time
     *
     * @mbg.generated
     */
    public Date getRawAddTime() {
        return rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.raw_add_time
     *
     * @param rawAddTime the value for user_base_info.raw_add_time
     *
     * @mbg.generated
     */
    public void setRawAddTime(Date rawAddTime) {
        this.rawAddTime = rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.raw_update_time
     *
     * @return the value of user_base_info.raw_update_time
     *
     * @mbg.generated
     */
    public Date getRawUpdateTime() {
        return rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.raw_update_time
     *
     * @param rawUpdateTime the value for user_base_info.raw_update_time
     *
     * @mbg.generated
     */
    public void setRawUpdateTime(Date rawUpdateTime) {
        this.rawUpdateTime = rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", realName=").append(realName);
        sb.append(", mobileNumber=").append(mobileNumber);
        sb.append(", certNo=").append(certNo);
        sb.append(", type=").append(type);
        sb.append(", state=").append(state);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", rawAddTime=").append(rawAddTime);
        sb.append(", rawUpdateTime=").append(rawUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}